### ISSUE TITLE
Action step: Validate change

### ISSUE THREAD

**Issue by abose** [aicore/contributor-license-agreement#27]
- [x] Verify that the row added in the table is valid syntax.
- [x] Verify that the GitHub id provided in the table is the GitHub ID raising the pull request.
- [x] Verify that the date mentioned in the table is valid and within one week of the pull request submission date.
- [x] User has not signed the CLA before in either personal or employer capacity.
- [x] Comment on the pull request if there are any violations of the above rules.
- [x] Date validations.
- [x] Do not fail validation on the first error, print all errors and finally fail the validation

Port in changes from https://github.com/brackets-cont/contributor-license-agreement/pull/9

**Comment by abose** [comment]
Check these links to understand how to comment on pull requests:
1. https://github.com/aicore/GithubActionTemplates/blob/main/.github/workflows/pull_request_post_processor.yml
2. https://github.com/aicore/GithubActionTemplates/blob/main/.github/workflows/python/pull_request_comment.py

**Comment by psdhanesh7** [comment]
> * [x]  Verify that the row added in the table is valid syntax.
> * [x]  Verify that the GitHub id provided in the table is the GitHub ID raising the pull request.
> * [x]  Verify that the date mentioned in the table is valid and within one week of the pull request submission date.
> * [ ]  User has not signed the CLA before in either personal or employer capacity.
> * [x]  Comment on the pull request if there are any violations of the above rules.
> * [x]  Date validations.
> * [x]  Do not fail validation on the first error, print all errors and finally fail the validation
> 
> Port in changes from [brackets-cont/contributor-license-agreement#9](https://github.com/brackets-cont/contributor-license-agreement/pull/9)

**Comment by psdhanesh7** [comment]
> * [x]  Verify that the row added in the table is valid syntax.
> * [x]  Verify that the GitHub id provided in the table is the GitHub ID raising the pull request.
> * [x]  Verify that the date mentioned in the table is valid and within one week of the pull request submission date.
> * [x]  User has not signed the CLA before in either personal or employer capacity.
> * [x]  Comment on the pull request if there are any violations of the above rules.
> * [x]  Date validations.
> * [x]  Do not fail validation on the first error, print all errors and finally fail the validation
> 
> Port in changes from [brackets-cont/contributor-license-agreement#9](https://github.com/brackets-cont/contributor-license-agreement/pull/9)

**Comment by abose** [comment]
Closing as done. Thanks @psdhanesh7 for the changes
